version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: db_comentarios_api
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: blogdb
      MYSQL_USER: administrador
      MYSQL_PASSWORD: pumas2025
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
